# Generated by Django 5.2.1 on 2025-05-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="attendance",
            field=models.DecimalField(decimal_places=1, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name="customuser",
            name="grade",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
