# Generated by Django 5.2.1 on 2025-05-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0002_customuser_attendance_customuser_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="colour",
            field=models.CharField(
                choices=[("student", "Student"), ("staff", "Staff")],
                default="#7f32a8",
                max_length=10,
            ),
        ),
    ]
