# Generated by Django 5.2.1 on 2025-05-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0003_customuser_colour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="colour",
            field=models.CharField(
                choices=[
                    ("#326ba8", "Blue"),
                    ("#ba2f2f", "Red"),
                    ("#288a3d", "Green"),
                    ("#7f32a8", "Purple"),
                    ("#d99221", "Orange"),
                ],
                default="#d99221",
                max_length=10,
            ),
        ),
    ]
